import { MapaDatos } from '@comun/type/mapeo-data.type';

export const FiltrosDetalleAporteDetalle: MapaDatos[] = [
  {
    nombre: 'ID',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'Identificacion',
    nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
    nombreFiltroRelacion: 'aporte_contrato__contrato__contacto__numero_identificacion',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
  // {
  //   nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
  //   nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
  //   nombreFiltroRelacion: 'CONTRATO__CONTACTO__NUMERO_IDENTIFICACION',
  //   campoTipo: 'CharField',
  //   visibleTabla: true,
  //   visibleFiltro: true,
  //   ordenable: false,
  // },
  {
    nombre: 'Empleado',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'Contrato',
    nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
    nombreFiltroRelacion: 'aporte_contrato__contrato_id',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
  {
    nombre: 'ING',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'RET',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VSP',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VST',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'SLN',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'IGE',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'LMA',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VAC',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'LRM',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'D_IRP',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'SI',
    campoTipo: 'Booleano',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'Salario',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'H',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'D_P',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'D_S',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'D_R',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'D_C',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'BC_P',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'BC_S',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'BC_R',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'BC_C',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_P',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_S',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_R',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_C',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_S',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'T_ICBF',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_P',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'F_SOL',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'F_SUB',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VOL_AFI',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VOL_APO',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_S',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_R',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_C',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_SENA',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'C_ICBF',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'Total',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
];

export const FiltrosDetalleAporteContratos: MapaDatos[] = [
  {
    nombre: 'ID',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
    nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
    nombreFiltroRelacion: 'CONTRATO__CONTACTO__NUMERO_IDENTIFICACION',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
];
