import { GenDocumentoImpuesto } from "./gen-documento-impuesto.interface"

export interface GenDocumentoDetalle {
    id: number
    tipo_registro: string
    item: number
    item_nombre: string
    cuenta: any
    cuenta_codigo: string
    cuenta_nombre: string
    cantidad: number
    cantidad_operada: number
    cantidad_afectada: number
    cantidad_pendiente: number
    precio: number
    pago: number
    pago_operado: number
    porcentaje: number
    porcentaje_descuento: number
    descuento: number
    subtotal: number
    total_bruto: number
    base: number
    base_impuesto: number
    impuesto: number
    impuesto_retencion: number
    impuesto_operado: number
    total: number
    hora: number
    dias: number
    devengado: number
    deduccion: number
    operacion: number
    operacion_inventario: number
    operacion_remision: number
    base_cotizacion: number
    base_prestacion: number
    base_prestacion_vacacion: number
    documento_afectado_id: any
    documento_afectado_documento_tipo_nombre: string
    documento_afectado_numero: string
    documento_afectado_contacto_nombre_corto: string
    documento_detalle_afectado_id: any
    contacto_id: any
    contacto_nombre_corto: string
    naturaleza: any
    detalle?: string
    numero: any
    concepto_id: any
    concepto_nombre: string
    credito_id: any
    grupo_id: any
    grupo_nombre: string
    almacen_id: number
    almacen_nombre: string[]
    documento_id: number
    documento_numero: any
    documento_fecha: string
    activo_id: any
    activo_codigo: string
    activo_nombre: string
    impuestos: GenDocumentoImpuesto[]
  }