export interface GenDocumentoDetalle {
    id: number
    documento_id: number
    tipo_registro: string
    item: any
    item_nombre: string
    cuenta: number
    cuenta_codigo: string
    cuenta_nombre: string
    cantidad: number
    cantidad_operada: number
    precio: number
    pago: number
    pago_operado: number
    porcentaje: number
    porcentaje_descuento: number
    descuento: number
    subtotal: number
    total_bruto: number
    base: number
    base_impuesto: number
    impuesto: number
    impuesto_retencion: number
    impuesto_operado: number
    total: number
    hora: number
    dias: number
    devengado: number
    deduccion: number
    operacion: number
    operacion_inventario: number
    base_cotizacion: number
    base_prestacion: number
    documento_afectado_id: number
    documento_afectado_documento_tipo_nombre: string
    documento_afectado_numero: number
    documento_afectado_contacto_nombre_corto: string
    contacto_id: number
    contacto_nombre_corto: string
    naturaleza: string
    detalle: any
    numero: number
    concepto_id: any
    concepto_nombre: string
    credito_id: any
    grupo_id: any
    grupo_nombre: string
    almacen_id: any
    almacen_nombre: string
    documento_numero: number
    documento_fecha: string
  }
  