import { MapeoAdministrador } from '@comun/type/mapeo-administradores.type';

export const mapeo: MapeoAdministrador = {
  GenContacto: {
    modulo: 'general',
    modelo: 'contacto',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'IDENTIFICACION_ABREVIATURA',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'NUMERO_IDENTIFICACION',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'DIGITO_VERIFICACION',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'NOMBRE_CORTO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CORREO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'DIRECCION',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'NOMBRE1',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'NOMBRE2',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'APELLIDO1',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'APELLIDO2',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CODIGO_POSTAL',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'TELEFONO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CELULAR',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CLIENTE',
        nombreAbreviado: 'CLI',
        toolTip: 'CLIENTE',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'PROVEEDOR',
        nombreAbreviado: 'PRO',
        toolTip: 'PROVEEDOR',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'EMPLEADO',
        nombreAbreviado: 'EMP',
        toolTip: 'EMPLEADO',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'BARRIO',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CODIGO_CIUU',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CIUDAD_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'REGIMEN_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'TIPO_PERSONA',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  GenItem: {
    modulo: 'general',
    modelo: 'Item',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'REFERENCIA',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'PRECIO',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        aplicaFormatoNumerico: true,
      },
      {
        nombre: 'COSTO',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        aplicaFormatoNumerico: true,
      },
      {
        nombre: 'PRODUCTO',
        campoTipo: 'Booleano',
        visibleTabla: false,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'SERVICIO',
        campoTipo: 'Booleano',
        visibleTabla: false,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'INVENTARIO',
        toolTip: 'INVENTARIO',
        nombreAbreviado: 'INVENTARIO_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'NEGATIVO',
        toolTip: 'NEGATIVO',
        nombreAbreviado: 'NEGATIVO_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'EXISTENCIA',
        toolTip: 'EXISTENCIA',
        nombreAbreviado: 'EXISTENCIA_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'REMISION',
        toolTip: 'REMISION',
        nombreAbreviado: 'REMISION_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'DISPONIBLE',
        toolTip: 'DISPONIBLE',
        nombreAbreviado: 'DISPONIBLE_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
    ],
  },
  GenResolucion: {
    modulo: 'general',
    modelo: 'resolucion',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'PREFIJO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'NUMERO',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CONSECUTIVO_DESDE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CONSECUTIVO_HASTA',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'FECHA_DESDE',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'FECHA_HASTA',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CLAVE_TECNICA',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'SET_PRUEBA',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  GenPrecio: {
    modulo: 'general',
    modelo: 'precio',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'TIPO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'FECHA_VENCE',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
    ],
  },
  GenAsesor: {
    modulo: 'general',
    modelo: 'asesor',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE_CORTO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CORREO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CELULAR',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  GenSede: {
    modulo: 'general',
    modelo: 'sede',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'GRUPO_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  HumContrato: {
    modulo: 'humano',
    modelo: 'HumContrato',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CONTRATO_TIPO_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CONTACTO_ID',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
        nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
        nombreFiltroRelacion: 'contacto__numero_identificacion',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
      {
        nombre: 'CONTACTO_NOMBRE_CORTO',
        campoTipo: 'Fk',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
        esFk: true,
        modeloFk: 'GenContacto',
      },
      {
        nombre: 'FECHA_DESDE',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'FECHA_HASTA',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CONTRATO_TIPO',
        campoTipo: 'CharField',
        visibleTabla: false,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        nombre: 'GRUPO_NOMBRE',
        campoTipo: 'Fk',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
        esFk: true,
        modeloFk: 'HumGrupo',
      },
      {
        nombre: 'SALARIO',
        campoTipo: 'FloatField',
        visibleTabla: true,
        visibleFiltro: false,
        aplicaFormatoNumerico: true,
        ordenable: false,
      },
      {
        nombre: 'ESTADO_TERMINADO',
        nombreAbreviado: 'ESTADO_TERMINADO_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
    ],
  },
  HumConcepto: {
    modulo: 'humano',
    modelo: 'HumConcepto',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'PORCENTAJE',
        campoTipo: 'Porcentaje',
        aplicaFormatoNumerico: true,
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        nombre: 'INGRESO_BASE_COTIZACION',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        nombre: 'INGRESO_BASE_PRESTACION',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        nombre: 'ORDEN',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
    ],
  },
  HumGrupo: {
    modulo: 'humano',
    modelo: 'HumGrupo',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'PERIODO_NOMBRE',
        nombreAbreviado: 'PERIODO_ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'PERIODO_DIAS',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  HumCargo: {
    modulo: 'humano',
    modelo: 'HumCargo',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'ESTADO_INACTIVO',
        nombreAbreviado: 'ESTADO_INACTIVO_ABREVIATURA',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: false,
      },
    ],
  },
  HumSucursal: {
    modulo: 'humano',
    modelo: 'HumSucursal',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  GenCuentaBanco: {
    modulo: 'general',
    modelo: 'CuentaBanco',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CUENTA_BANCO_TIPO_NOMBRE',
        campoTipo: 'Fk',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        esFk: true,
        modeloFk: 'GenCuentaBanco',
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NUMERO_CUENTA',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
        alinearAlaIzquierda: false,
      },
      {
        nombre: 'CUENTA_BANCO_CLASE_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CUENTA_CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CUENTA_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  ConCuenta: {
    modulo: 'contabilidad',
    modelo: 'ConCuenta',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'EXIGE_BASE',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'EXIGE_CONTACTO',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'EXIGE_GRUPO',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'PERMITE_MOVIMIENTO',
        campoTipo: 'Booleano',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  ConComprobante: {
    modulo: 'contabilidad',
    modelo: 'ConComprobante',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'PERMITEASIENTO',
        campoTipo: 'Booleano',
        visibleTabla: false,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  ConGrupo: {
    modulo: 'contabilidad',
    modelo: 'ConGrupo',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  GenFormaPago: {
    modulo: 'general',
    modelo: 'GenFormaPago',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CUENTA_CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'CUENTA_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  ConActivo: {
    modulo: 'contabilidad',
    modelo: 'ConActivo',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'CODIGO',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'FECHA_COMPRA',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'FECHA_ACTIVACION',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'FECHA_BAJA',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'GRUPO_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'ACTIVO_GRUPO_NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'VALOR_COMPRA',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        nombre: 'DEPRECIACION_INICIAL',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
    ],
  },
  InvAlmacen: {
    modulo: 'inventario',
    modelo: 'InvAlamacen',
    tipo: 'Administrador',
    datos: [
      {
        nombre: 'ID',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        nombre: 'NOMBRE',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
};
