import { MapeoDocumentos } from '@comun/type/mapeo-documentos.type';
import { documento100 } from './documentos/100.documento';
import { documento101 } from './documentos/101.documento';
import { documento102 } from './documentos/102.documento';
import { documento103 } from './documentos/103.documento';
import { documento104 } from './documentos/104.documento';
import { documento105 } from './documentos/105.documento';
import { documento200 } from './documentos/200.documento';
import { documento201 } from './documentos/201.documento';
import { documento300 } from './documentos/300.documento';
import { documento301 } from './documentos/301.documento';
import { documento302 } from './documentos/302.documento';
import { documento303 } from './documentos/303.documento';
import { documento304 } from './documentos/304.documento';
import { documento400 } from './documentos/400.documento';
import { documento401 } from './documentos/401.documento';
import { documento500 } from './documentos/500.documento';
import { documento501 } from './documentos/501.documento';
import { documento601 } from './documentos/601.documento';
import { documento603 } from './documentos/603.documento';
import { documento701 } from './documentos/701.documento';
import { documento702 } from './documentos/702.documento';
import { documento703 } from './documentos/703.documento';
import { documentoConMovimiento } from './documentos/ConMovimiento.documento';
import { documentoHumAporte } from './documentos/humAporte.documento';
import { documentoHumProgramacion } from './documentos/humProgramacion.documento';

export const documentos: MapeoDocumentos = {
  100: documento100,
  101: documento101,
  102: documento102,
  103: documento103,
  104: documento104,
  105: documento105,
  200: documento200,
  201: documento201,
  300: documento300,
  301: documento301,
  302: documento302,
  303: documento303,
  304: documento304,
  400: documento400,
  401: documento401,
  500: documento500,
  501: documento501,
  601: documento601,
  602: documento601,
  603: documento603,
  701: documento701,
  702: documento702,
  703: documento703,
  HumProgramacion: documentoHumProgramacion,
  HumAporte: documentoHumAporte,
  ConMovimiento: documentoConMovimiento,
};


// export const documentos: MapeoDocumentos = {
//   100: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       esFk: true,
//       modeloFk: 'GenContacto',
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO',
//       nombreAbreviado: 'ESTADO_ELECTRONICO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   101: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   102: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   103: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'contacto__numero_identificacion',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       esFk: true,
//       modeloFk: 'GenContacto',
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO',
//       nombreAbreviado: 'ESTADO_ELECTRONICO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   104: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       esFk: true,
//       modeloFk: 'GenContacto',
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO',
//       nombreAbreviado: 'ESTADO_ELECTRONICO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   200: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       esFk: true,
//       modeloFk: 'GenContacto',
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   201: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       esFk: true,
//       modeloFk: 'GenContacto',
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   300: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contacto__nombre_corto',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO_EVENTO',
//       nombreAbreviado: 'ESTADO_ELECTRONICO_EVENTO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   301: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   302: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   303: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL_BRUTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO',
//       nombreAbreviado: 'ELE',
//       toolTip: 'ESTADOELECTRONICO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   304: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   400: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   401: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   500: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   501: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   601: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'SOPORTE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'SUBTOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'IMPUESTO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       aplicaFormatoNumerico: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   701: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'DOCUMENTO_TIPO_NOMBRE',
//       nombreAbreviado: 'TIPO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       nombreAbreviado: 'DESDE',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_HASTA',
//       nombreAbreviado: 'HASTA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_ID',
//       campoTipo: 'Fk',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'CONTACTO__NUMERO_IDENTIFICACION',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contacto__nombre_corto',
//       nombreAbreviado: 'EMPLEADO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'SALARIO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DEVENGADO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DEDUCCION',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   702: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       nombreAbreviado: 'DESDE',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_HASTA',
//       nombreAbreviado: 'HASTA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTACTO_ID',
//       nombreAbreviadoFiltro: 'CONTACTO_ID_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__id',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//       esFk: true,
//     },
//     {
//       nombre: 'CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'CONTACTO__NUMERO_IDENTIFICACION',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
//       nombreAbreviado: 'EMPLEADO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATO_ID',
//       nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
//       nombreFiltroRelacion: 'contrato__id',
//       nombreAbreviado: 'CONT',
//       toolTip: 'CONTRATO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'SALARIO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'BASE_COTIZACION',
//       nombreAbreviado: 'IBC',
//       toolTip: 'INGRESOBASECOTIZACION',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'BASE_PRESTACION',
//       nombreAbreviado: 'IBP',
//       toolTip: 'INGRESOBASEPRESTACION',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DEVENGADO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DEDUCCION',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       toolTip: 'ESTADO_APROBADO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ANULADO',
//       nombreAbreviado: 'ESTADO_ANULADO_ABREVIATURA',
//       toolTip: 'ESTADO_ANULADO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_ELECTRONICO',
//       nombreAbreviado: 'ELE',
//       toolTip: 'ESTADOELECTRONICO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_CONTABILIZADO',
//       nombreAbreviado: 'ESTADO_CONTABILIZADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   HumProgramacion: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NOMBRE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'PAGO_TIPO_NOMBRE',
//       nombreAbreviadoFiltro: 'PAGO_TIPO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'pago_tipo__nombre',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'GRUPO_NOMBRE',
//       nombreAbreviadoFiltro: 'GRUPO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'grupo__nombre',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'PERIODO_NOMBRE',
//       nombreAbreviadoFiltro: 'PERIODO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'periodo__nombre',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_DESDE',
//       nombreAbreviado: 'DESDE',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_HASTA',
//       nombreAbreviado: 'HASTA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'DIAS',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATOS',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'ESTADO_APROBADO',
//       nombreAbreviado: 'ESTADO_APROBADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   HumAdicional: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_ID',
//       nombreAbreviadoFiltro: 'CONTACTO_ID_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__id',
//       nombreAbreviado: 'CODIGO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__numero_identificacion',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_ID',
//       nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
//       nombreFiltroRelacion: 'contrato__id',
//       nombreAbreviado: 'CONT',
//       campoTipo: 'IntegerField',
//       toolTip: 'CONTRATO',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONCEPTO',
//       campoTipo: 'CharField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONCEPTO_ID',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONCEPTO_NOMBRE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'VALOR',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DETALLE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'APLICA_DIA_LABORADO',
//       nombreAbreviado: 'APLICA_DIA_LABORADO_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATO',
//       campoTipo: 'CharField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'INACTIVO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'INACTIVO_PERIODO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   HumCredito: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_ID',
//       campoTipo: 'CharField',
//       visibleTabla: false,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__numero_identificacion',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_INICIO',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CUOTA',
//       nombreAbreviado: 'VALOR_CUOTA',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       aplicaFormatoNumerico: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CUOTA_ACTUAL',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       aplicaFormatoNumerico: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CANTIDAD_CUOTAS',
//       alinearAlaIzquierda: true,
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'ABONO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'SALDO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'VALIDAR_CUOTAS',
//       nombreAbreviado: 'VALIDAR_CUOTAS_ABREVIATURA',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'PAGADO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'INACTIVO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'INACTIVO_PERIODO',
//       campoTipo: 'Booleano',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//   ],
//   HumNovedad: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NOVEDAD_TIPO_NOMBRE',
//       nombreAbreviadoFiltro: 'NOVEDAD_TIPO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'novedad_tipo__nombre',
//       nombreAbreviado: 'TIPO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_ID',
//       nombreAbreviado: 'CODIGO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NUMERO_IDENTIFICACION',
//       nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__numero_identificacion',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_EMPLEADO_FILTRO',
//       nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'CONTRATO_ID',
//       nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
//       nombreFiltroRelacion: 'contrato__id',
//       nombreAbreviado: 'CONTRATO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_DESDE',
//       nombreAbreviado: 'DESDE',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA_HASTA',
//       nombreAbreviado: 'HASTA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'DIAS',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'TOTAL',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//   ],
//   HumAporte: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'MES',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'ANIO',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'SUCURSAL_NOMBRE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'EMPLEADOS',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'CONTRATOS',
//       nombreAbreviado: 'CONTRS',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//     {
//       nombre: 'LINEAS',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       ordenable: false,
//     },
//   ],
//   ConMovimiento: [
//     {
//       nombre: 'ID',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'NUMERO',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'COMPROBANTE',
//       nombreAbreviadoFiltro: 'COMPROBANTE_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'comprobante__nombre',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'FECHA',
//       campoTipo: 'DateField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//       stylePersonalizado: { width: '120px' },
//     },
//     {
//       nombre: 'CONTACTO_NOMBRE_CORTO',
//       nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'contacto__nombre_corto',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: false,
//       stylePersonalizado: { width: '300px' },
//     },
//     {
//       nombre: 'CUENTA',
//       nombreAbreviadoFiltro: 'CUENTA_CODIGO_FILTRO',
//       nombreFiltroRelacion: 'cuenta__codigo',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'GRUPO',
//       nombreAbreviadoFiltro: 'GRUPO_NOMBRE_FILTRO',
//       nombreFiltroRelacion: 'grupo__nombre',
//       campoTipo: 'IntegerField',
//       visibleTabla: true,
//       visibleFiltro: true,
//       ordenable: true,
//     },
//     {
//       nombre: 'DEBITO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'CREDITO',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'BASE',
//       campoTipo: 'FloatField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: true,
//       ordenable: false,
//     },
//     {
//       nombre: 'DETALLE',
//       campoTipo: 'CharField',
//       visibleTabla: true,
//       visibleFiltro: false,
//       aplicaFormatoNumerico: false,
//       ordenable: false,
//       stylePersonalizado: { width: '300px' },
//     },
//   ],
// };
