export interface RespuestaContabilizarLista {
    id: number
    numero: number
    fecha: string
    fecha_vence: string
    fecha_contable: string
    fecha_hasta: any
    descuento: number
    base_impuesto: number
    subtotal: number
    impuesto: number
    impuesto_retencion: number
    impuesto_operado: number
    total_bruto: number
    total: number
    afectado: number
    pendiente: number
    devengado: number
    deduccion: number
    base_cotizacion: number
    base_prestacion: number
    salario: number
    contacto_id: number
    contacto_numero_identificacion: string
    contacto_nombre_corto: string
    documento_tipo_id: number
    documento_tipo_nombre: string
    metodo_pago: number
    estado_aprobado: boolean
    estado_contabilizado: boolean
    estado_anulado: boolean
    estado_electronico: boolean
    estado_electronico_enviado: boolean
    estado_electronico_notificado: boolean
    estado_electronico_evento: boolean
    estado_electronico_descartado: boolean
    comentario: any
    soporte: any
    orden_compra: any
    cue: any
    referencia_cue: any
    referencia_numero: any
    referencia_prefijo: any
    empresa: number
    resolucion: any
    documento_referencia: any
    plazo_pago: number
    asesor_id: any
    asesor_nombre_corto: string
    sede_id: any
    sede_nombre: string
    programacion_detalle_id: any
    contrato_id: any
    cuenta_banco_id: any
    cuenta_banco_nombre: string
    comprobante_id: any
    comprobante_nombre: string
    grupo_contabilidad_id: any
    grupo_contabilidad_nombre: string
  }
  