import { MapeoDocumento } from '@comun/type/mapeo-documentos.type';

export const documentoConMovimiento: MapeoDocumento[] = [
  {
    nombre: 'ID',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'NUMERO',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'COMPROBANTE',
    nombreAbreviadoFiltro: 'COMPROBANTE_NOMBRE_FILTRO',
    nombreFiltroRelacion: 'comprobante__nombre',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'FECHA',
    campoTipo: 'DateField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
    stylePersonalizado: { width: '120px' },
  },
  {
    nombre: 'CONTACTO_NOMBRE_CORTO',
    nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
    nombreFiltroRelacion: 'contacto__nombre_corto',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
    stylePersonalizado: { width: '300px' },
  },
  {
    nombre: 'CUENTA',
    nombreAbreviadoFiltro: 'CUENTA_CODIGO_FILTRO',
    nombreFiltroRelacion: 'cuenta__codigo',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'GRUPO',
    nombreAbreviadoFiltro: 'GRUPO_NOMBRE_FILTRO',
    nombreFiltroRelacion: 'grupo__nombre',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'DEBITO',
    campoTipo: 'FloatField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
  {
    nombre: 'CREDITO',
    campoTipo: 'FloatField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
  {
    nombre: 'BASE',
    campoTipo: 'FloatField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
  {
    nombre: 'DETALLE',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: false,
    ordenable: false,
    stylePersonalizado: { width: '300px' },
  },
];
