import { MapeoDocumento } from '@comun/type/mapeo-documentos.type';

export const documentoHumAdicional: MapeoDocumento[] = [
  {
    nombre: 'ID',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_CONTACTO_ID',
    nombreAbreviadoFiltro: 'CONTACTO_ID_FILTRO',
    nombreFiltroRelacion: 'contrato__contacto__id',
    nombreAbreviado: 'CODIGO',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_CONTACTO_NUMERO_IDENTIFICACION',
    nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
    nombreFiltroRelacion: 'contrato__contacto__numero_identificacion',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_CONTACTO_NOMBRE_CORTO',
    nombreAbreviadoFiltro: 'CONTACTO_NOMBRE_FILTRO',
    nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_ID',
    nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
    nombreFiltroRelacion: 'contrato__id',
    nombreAbreviado: 'CONT',
    campoTipo: 'IntegerField',
    toolTip: 'CONTRATO',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONCEPTO',
    campoTipo: 'CharField',
    visibleTabla: false,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'CONCEPTO_ID',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'CONCEPTO_NOMBRE',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'VALOR',
    campoTipo: 'FloatField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
  {
    nombre: 'DETALLE',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'APLICA_DIA_LABORADO',
    nombreAbreviado: 'APLICA_DIA_LABORADO_ABREVIATURA',
    campoTipo: 'Booleano',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
  {
    nombre: 'CONTRATO',
    campoTipo: 'CharField',
    visibleTabla: false,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
  {
    nombre: 'INACTIVO',
    campoTipo: 'Booleano',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
];
