import { MapeoDocumento } from '@comun/type/mapeo-documentos.type';

export const documentoHumNovedad: MapeoDocumento[] = [
  {
    nombre: 'ID',
    campoTipo: 'IntegerField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'NOVEDAD_TIPO_NOMBRE',
    nombreAbreviadoFiltro: 'NOVEDAD_TIPO_NOMBRE_FILTRO',
    nombreFiltroRelacion: 'novedad_tipo__nombre',
    nombreAbreviado: 'TIPO',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: false,
  },
  {
    nombre: 'CONTRATO_CONTACTO_ID',
    nombreAbreviado: 'CODIGO',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'CONTRATO_CONTACTO_NUMERO_IDENTIFICACION',
    nombreAbreviadoFiltro: 'CONTACTO_IDENTIFICACION_FILTRO',
    nombreFiltroRelacion: 'contrato__contacto__numero_identificacion',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_CONTACTO_NOMBRE_CORTO',
    nombreAbreviadoFiltro: 'CONTACTO_EMPLEADO_FILTRO',
    nombreFiltroRelacion: 'contrato__contacto__nombre_corto',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'CONTRATO_ID',
    nombreAbreviadoFiltro: 'CONTRATO_ID_FILTRO',
    nombreFiltroRelacion: 'contrato__id',
    nombreAbreviado: 'CONTRATO',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'FECHA_DESDE',
    nombreAbreviado: 'DESDE',
    campoTipo: 'DateField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'FECHA_HASTA',
    nombreAbreviado: 'HASTA',
    campoTipo: 'DateField',
    visibleTabla: true,
    visibleFiltro: true,
    ordenable: true,
  },
  {
    nombre: 'DIAS',
    campoTipo: 'CharField',
    visibleTabla: true,
    visibleFiltro: false,
    ordenable: false,
  },
  {
    nombre: 'TOTAL',
    campoTipo: 'FloatField',
    visibleTabla: true,
    visibleFiltro: false,
    aplicaFormatoNumerico: true,
    ordenable: false,
  },
];
